### ISSUE TITLE
Display daily snack/lunch foods available at DNHS

### ISSUE THREAD

**Issue by yajatyadav** [yajatyadav/spring_portfolio#15]
- Assigned to Flora

**Comment by florayuan18** [comment]
![image](https://user-images.githubusercontent.com/52616551/133032813-e3d905d9-6a75-4b4d-9417-c37a54dac003.png)

**Comment by florayuan18** [comment]
![image](https://user-images.githubusercontent.com/52616551/133033029-a627d40c-0e9f-4117-90cb-fdaec99f6029.png)

**Comment by florayuan18** [comment]
![image](https://user-images.githubusercontent.com/52616551/133033085-c39b72b2-c896-4d10-99f7-a285cc67c7dc.png)
![image](https://user-images.githubusercontent.com/52616551/133033120-adf2f2ab-e9d4-4808-aa33-2fab51ef2da0.png)
