### ISSUE TITLE
Teacher Planning Meeting - 09/15

### ISSUE THREAD

**Issue by florayuan18** [yajatyadav/spring_portfolio#34]

**Comment by jm1021** [comment]
Did some analysis and presentation design.   Working on cards, calculating price.  Color coding tables.  1.0

**Comment by jm1021** [comment]
Video was good.  It looks like you are really focused on project.  Most of your work I could tell the tight association of the work.  However, the README and your Scrum Board need some work.  The overall experience is frustrating and hard to find materials and their meaning.  Scrum board had nothing in Review column, which I could interpret as not doing any work.  Tangibles are alway pictures on Issues, no links to code.  

 Team score is 1.5/2.0

**Comment by jm1021** [comment]
Individual work is really difficult to figure out.  I resorted looking at commits.  Devam provides no information in comments.  You have a feeling of not being concerned about viewers of information.  1.7/2.0

**Comment by jm1021** [comment]
At this point I am frustrated.  I see you all completed college board requirements from their presentation.  Section for journals uses title "Document", Kyle has confusion as well as he put other information in this section and gave himself a 7/7 where everyone else did 5/5.  This is another frustration as I don't know what I am looking at.

4.75 of 5

**Comment by jm1021** [comment]
Generally, you need a Navigator or Tester role.   It seems like I am the one doing it.
